#ifndef SIGN_ROUTE_CONFIG_H
#define SIGN_ROUTE_CONFIG_H
/* Geometry/time bounds are navigation warnings; all-white keeps searching. */
#define SIGN_PROBE_MAX_MM 80L
#define SIGN_PROBE_TIMEOUT_MS 1800U
#ifndef SIGN_PROBE_HOLD_MS
#define SIGN_PROBE_HOLD_MS 10000U
#endif
#define SIGN_CAPTURE_MS 30U
#define SIGN_PROBE_CENTER_CLEAR_MS 120U
#define SIGN_SAMPLE_MAX_GAP_MS 50U
#define SIGN_SELECT_TIMEOUT_MS 2500U
#define SIGN_SELECT_MAX_YAW_MDEG 135000L
#define SIGN_ARC_MIN_MM 150L
#define SIGN_ARC_MAX_MM 3000L
#define SIGN_ARC_MIN_YAW_MDEG 90000L
#define SIGN_ARC_MAX_YAW_MDEG 270000L
#define SIGN_ARC_TIMEOUT_MS 20000U
#define SIGN_EXIT_CLEAR_MM 60L
#define SIGN_EXIT_CLEAR_TIMEOUT_MS 2000U
#define SIGN_ROUTE_PWM 2200
#endif
